### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ibnumohtaram** [harrasyong/MusicApp#2]
Put all yr code in github i want to review

**Comment by Sneharavichandhar** [comment]
sir that full coding is in progress .

**Comment by harrasyong** [comment]
we otw to finish the code sir after that we will send to you sir! @Sneharavichandhar @harrasyong @saffuan1 @ibnumohtaram

**Comment by saffuan1** [comment]
we expect to finish the code at the night and send it tomorrow morning after the coding is fully functional... @Sneharavichandhar @harrasyong @ibnumohtaram
